const VALIDATION_ERROR = 400;
const AUTH_ERROR = 401;
const FORBIDDEN_ERROR = 403;
const NOTFOUND_ERROR = 404;
const CONFLICT_ERROR = 409;
const SERVER_ERROR = 500;

module.exports = {
  VALIDATION_ERROR,
  AUTH_ERROR,
  FORBIDDEN_ERROR,
  NOTFOUND_ERROR,
  CONFLICT_ERROR,
  SERVER_ERROR,
};
